language: php

sudo: false

php:
  - 7.2
  - 7.3

env:
  global:
    - setup=basic

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: setup=lowest
    - php: 7.3
      env: setup=stable


before_install:
  - composer self-update
  - composer clear-cache

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer update --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script: vendor/bin/phpunit
